site_name: Troubleshooting
site_url: https://rotc-kais.github.io/troubleshooting-docs
repo_url: https://github.com/rotc-kais/troubleshooting-docs
repo_name: troubleshooting-docs
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes 
    - navigation.expand
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - announce.dismiss
  palette:
    - scheme: default
      primary: blue
      accent: indigo

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

# 顶部导航（按模块分类）
nav:
  - Overview: index.md
  - ACP:
    - acp/index.md                
    - Network:
      - acp/network/index.md
      - Calico: acp/network/calico/index.md
      - Kube-OVN: acp/network/kube-ovn/index.md
      - Ingress: 
        - acp/network/ingress/index.md
        - alb: acp/network/ingress/alb/index.md
    - Storage:
      - acp/storage/index.md
      - Ceph: acp/storage/ceph/index.md
      - NFS: acp/storage/nfs/index.md
  - AIT:
    - ait/index.md
  - Middleware:
    - middleware/index.md
  - AI:
    - ai/index.md
  - DevOps:
    - devops/index.md
  - Others:
    - others/index.md

extra:
  social:
    - icon: material/github
      link: https://github.com/rotc-kais/troubleshooting-docs

